version: "3"
services:
  nginx:
    container_name: "nginx"
    depends_on:
      - frontend1
      - frontend2
      - frontend3
      - backend1
      - backend2
      - backend3
    expose:
      - "443"
    image: aoudaa/dkr-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/ssl:/etc/nginx/ssl
    restart: always

  frontend1:
    container_name: "frontend1"
    image: aoudaa/dkr-frontend
    env_file:
      - .env
    restart: on-failure
    volumes:
      - /app/node_modules
    ports:
      - "2998:3000"

  frontend2:
    container_name: "frontend2"
    image: aoudaa/dkr-frontend
    env_file:
      - .env
    restart: on-failure
    volumes:
      - /app/node_modules
    ports:
      - "2999:3000"

  frontend3:
    container_name: "frontend3"
    image: aoudaa/dkr-frontend
    env_file:
      - .env
    restart: on-failure
    volumes:
      - /app/node_modules
    ports:
      - "3000:3000"

  backend1:
    container_name: "backend1"
    image: aoudaa/dkr-backend
    env_file:
      - .env1
    restart: on-failure
    volumes:
      - /app/node_modules

  backend2:
    container_name: "backend2"
    image: aoudaa/dkr-backend
    env_file:
      - .env2
    restart: on-failure
    volumes:
      - /app/node_modules

  backend3:
    container_name: "backend3"
    image: aoudaa/dkr-backend
    env_file:
      - .env3
    restart: on-failure
    volumes:
      - /app/node_modules
