version: "3"
services:
  nginx:
    container_name: "nginx"
    depends_on:
      - frontend
      - backend1
      - backend2
      - backend3
    expose:
      - "443"
    image: aoudaa/dkr-nginx

    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/ssl:/etc/nginx/ssl

    restart: always

  frontend:
    container_name: "frontend"
    image: aoudaa/dkr-frontend
    env_file:
      - .env
    restart: on-failure
    volumes:
      - /app/node_modules

  backend1:
    container_name: "backend1"
    image: aoudaa/dkr-backend
    env_file:
      - .env1
    restart: on-failure
    volumes:
      - /app/node_modules

  backend2:
    container_name: "backend2"
    image: aoudaa/dkr-backend
    env_file:
      - .env2
    restart: on-failure
    volumes:
      - /app/node_modules

  backend3:
    container_name: "backend3"
    image: aoudaa/dkr-backend
    env_file:
      - .env3
    restart: on-failure
    volumes:
      - /app/node_modules
