# CI/CD Nginx

name: CI / CD Nginx

on:
  push:
    branches:
      - main
    paths-ignore:
      - './docker-compose.yml'

  pull_request:
    branches:
      - main

jobs:
  build_push_docker:
    name: Build Nginx For Prod files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Nginx For Prod files
        run: |
          docker build -t aoudaa/dkr-nginx:latest .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Nginx image

        run: |
          docker push aoudaa/dkr-nginx:latest

  deploy:
    name: Deploy Nginx For Prod files
    runs-on: ubuntu-latest
    needs: build_push_docker

    steps:
      - name: ssh into vm and run the script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/aoudaa/docker
            sh deployN.sh
